image: gitpod/workspace-base

tasks:

- name: Get the OMAMer database
  init: |
    cd /workspace
    curl -L -O "https://oma-stage.vital-it.ch/All/LUCA.h5"
    mv LUCA.h5 oma-omark/working_dir/DB/
- name: install mamba and omark
  init: |
    cd /workspace
    curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
    bash Mambaforge-$(uname)-$(uname -m).sh -b -p /workspace/conda && rm Mambaforge-$(uname)-$(uname -m).sh
    /workspace/conda/bin/mamba init bash

    source ${HOME}/.bashrc
    mamba create -n omark -c conda-forge python=3.9 -y
    mamba activate omark
    pip install omark
  command: |
    cd /workspace/oma-omark/working_dir
    /workspace/conda/bin/conda init bash
    echo 'condaa activate omark' >> ${HOME}/.bashrc
    source ${HOME}/.bashrc 
vscode:
  extensions:
    - anwar.papyrus-pdf

workspaceLocation: "/workspace"

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
